import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Sim Racing Alliance',
  description: 'How Sim Racing Alliance collects, uses, and stores driver data.',
};

const SECTION_HEADING =
  'font-display font-bold text-[24px] uppercase tracking-[-.5px] text-heading-subtitle mt-12 mb-4';
const SUBHEADING =
  'font-display font-bold text-[17px] uppercase tracking-[-.25px] text-txt mt-8 mb-3';
const BODY_TEXT = 'font-sans text-sm text-txt-2 leading-relaxed mb-4';
const LIST = 'font-sans text-sm text-txt-2 leading-relaxed list-disc pl-5 space-y-1.5 mb-4';

export default function PrivacyPage() {
  return (
    <section className="max-w-[880px] mx-auto px-7 pt-14 pb-24">
      <span className="block font-mono text-[15px] tracking-[.3em] uppercase text-gold mb-5">
        — Legal
      </span>
      <h1 className="font-display font-black text-[clamp(36px,5vw,60px)] uppercase leading-[.95] tracking-[-1px] text-txt mb-4">
        Privacy Policy
      </h1>
      <p className="font-mono text-xs text-txt-3 mb-10">Last Updated: July 28, 2026</p>

      <p className={BODY_TEXT}>
        Sim Racing Alliance (&ldquo;SRA,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;)
        respects the privacy of our members, drivers, website visitors, and community participants.
      </p>
      <p className={BODY_TEXT}>
        This Privacy Policy explains how we collect, use, disclose, retain, and protect information
        when you visit the Sim Racing Alliance website, create or manage a driver profile, connect a
        third-party account, participate in an SRA event or server, communicate with our staff, support
        the community, or otherwise interact with SRA.
      </p>
      <p className={BODY_TEXT}>
        This policy applies to information handled directly by SRA. Third-party platforms and services
        may maintain their own privacy policies and practices.
      </p>

      {/* ── Information We Collect ─────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Information We Collect</h2>
      <p className={BODY_TEXT}>
        We may collect information that you provide directly, information generated through your
        participation in SRA, and certain technical information collected automatically.
      </p>

      <h3 className={SUBHEADING}>Account and Profile Information</h3>
      <p className={BODY_TEXT}>
        When you create or manage an SRA profile or connect a third-party account, we may collect
        information such as:
      </p>
      <ul className={LIST}>
        <li>Your display name, username, or driver name</li>
        <li>Steam account identifier and profile information</li>
        <li>Discord account identifier and profile information</li>
        <li>Profile image or avatar</li>
        <li>Driver number</li>
        <li>Team, class, division, or series information</li>
        <li>Preferred racing platforms or simulations</li>
        <li>Account connection and authentication status</li>
        <li>Other profile information you choose to provide</li>
      </ul>
      <p className={BODY_TEXT}>
        Steam and Discord authentication is handled through those respective platforms. SRA does not
        ask you to provide your Steam or Discord password.
      </p>
      <p className={BODY_TEXT}>
        The specific information shared with SRA may depend on the permissions and settings displayed
        when you connect an account.
      </p>

      <h3 className={SUBHEADING}>Racing and Competition Information</h3>
      <p className={BODY_TEXT}>
        When you participate in SRA servers, races, championships, qualifying sessions, time trials, or
        other activities, we may collect and maintain information including:
      </p>
      <ul className={LIST}>
        <li>Event registrations and participation history</li>
        <li>Selected cars, classes, teams, and driver numbers</li>
        <li>Practice, qualifying, and race results</li>
        <li>Lap times, sector times, session data, and server activity</li>
        <li>Championship standings and statistics</li>
        <li>Driver ratings, rankings, classifications, and performance metrics</li>
        <li>Incident reports, stewarding decisions, warnings, penalties, and appeals</li>
        <li>Attendance and eligibility information</li>
        <li>
          Telemetry or other racing data requested for competition integrity, rule enforcement, or
          anti-cheat review
        </li>
        <li>Information generated by SRA servers, league tools, game servers, or connected competition platforms</li>
      </ul>
      <p className={BODY_TEXT}>
        This information may be used to administer events, maintain competitive integrity, calculate
        ratings and standings, assign divisions, enforce league rules, and preserve SRA&rsquo;s
        competitive history.
      </p>

      <h3 className={SUBHEADING}>Communications, Tickets, and Community Activity</h3>
      <p className={BODY_TEXT}>
        When you contact SRA, submit a ticket, communicate with staff, participate in moderation or
        stewarding processes, or otherwise engage with the community, we may collect:
      </p>
      <ul className={LIST}>
        <li>Messages and correspondence</li>
        <li>Support and administrative requests</li>
        <li>Incident reports and appeals</li>
        <li>Screenshots, video clips, replay files, telemetry, and other supporting evidence</li>
        <li>Moderation reports and disciplinary records</li>
        <li>Feedback, survey responses, and suggestions</li>
        <li>Information you include in Discord tickets, website forms, emails, or other submissions</li>
      </ul>
      <p className={BODY_TEXT}>
        Please do not submit sensitive personal information unless it is reasonably necessary and
        specifically requested through an appropriate process.
      </p>

      <h3 className={SUBHEADING}>Donations, Subscriptions, and Merchandise</h3>
      <p className={BODY_TEXT}>
        SRA may use third-party platforms to process donations, recurring community support,
        subscriptions, and merchandise purchases.
      </p>
      <p className={BODY_TEXT}>Depending on the service used, SRA may receive information such as:</p>
      <ul className={LIST}>
        <li>Your name</li>
        <li>Email address</li>
        <li>Username or account identifier</li>
        <li>Donation or subscription amount</li>
        <li>Membership or supporter status</li>
        <li>Transaction date and status</li>
        <li>Merchandise order or fulfillment information</li>
        <li>Information needed to provide supporter benefits</li>
      </ul>
      <p className={BODY_TEXT}>
        Payments are generally processed by the applicable third-party payment or commerce provider.
        SRA does not typically receive or store your complete payment card information.
      </p>

      <h3 className={SUBHEADING}>Information Collected Automatically</h3>
      <p className={BODY_TEXT}>
        When you visit the SRA website or use certain online services, technical and usage information
        may be collected automatically, including:
      </p>
      <ul className={LIST}>
        <li>IP address</li>
        <li>Browser type and version</li>
        <li>Device and operating system information</li>
        <li>Referring website or source</li>
        <li>Pages viewed</li>
        <li>Dates and times of visits</li>
        <li>Website interactions</li>
        <li>General geographic information derived from technical data</li>
        <li>Cookie identifiers and similar information</li>
        <li>Security, diagnostic, and server log information</li>
      </ul>
      <p className={BODY_TEXT}>
        We may use this information to operate the website, maintain security, identify technical
        problems, understand website usage, and improve SRA services.
      </p>

      {/* ── Public Competition and Community Information ──────────────── */}
      <h2 className={SECTION_HEADING}>Public Competition and Community Information</h2>
      <p className={BODY_TEXT}>
        Sim racing is a public and community-oriented activity. Certain information associated with
        participation in SRA may be publicly displayed, published, streamed, recorded, or shared.
      </p>
      <p className={BODY_TEXT}>This may include:</p>
      <ul className={LIST}>
        <li>Driver names, usernames, or display names</li>
        <li>Driver numbers, teams, cars, liveries, classes, and divisions</li>
        <li>Race registrations and event participation</li>
        <li>Lap times, results, standings, records, rankings, and ratings</li>
        <li>Championship history and statistics</li>
        <li>Penalties, stewarding outcomes, and competition-related rulings</li>
        <li>
          Gameplay footage, race broadcasts, commentary, interviews, and voice communications included
          in a broadcast
        </li>
        <li>Screenshots, clips, photographs, or community content submitted for publication</li>
      </ul>
      <p className={BODY_TEXT}>
        This information may appear on the SRA website, Discord community, livestreams, social media
        accounts, race broadcasts, partner platforms, or other public-facing SRA channels.
      </p>
      <p className={BODY_TEXT}>
        Competition results and historical records may remain publicly available after a member leaves
        the community or requests deletion of an account. Where reasonably possible, SRA may remove or
        de-identify personal profile information without compromising the integrity of historical
        competition records.
      </p>
      <p className={BODY_TEXT}>
        Members should avoid using personally identifying information as a public driver name or
        username unless they are comfortable with that information appearing publicly.
      </p>

      {/* ── How We Use Information ─────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>How We Use Information</h2>
      <p className={BODY_TEXT}>SRA may use information to:</p>
      <ul className={LIST}>
        <li>Create, authenticate, connect, and manage member profiles</li>
        <li>Connect Steam, Discord, and other supported platform accounts</li>
        <li>Register drivers for races, championships, and community events</li>
        <li>Operate game servers, practice servers, qualification servers, and time trials</li>
        <li>Track lap times, results, records, standings, and participation</li>
        <li>Calculate driver ratings, rankings, classifications, and division placements</li>
        <li>Administer stewarding, incident reviews, appeals, moderation, and rule enforcement</li>
        <li>Detect cheating, fraud, account misuse, or unauthorized activity</li>
        <li>Review telemetry or competition data when necessary</li>
        <li>Communicate event information, server details, rule updates, and community announcements</li>
        <li>Respond to support requests and administrative inquiries</li>
        <li>Manage donations, subscriptions, supporter benefits, and community recognition</li>
        <li>Produce livestreams, broadcasts, race reports, promotional content, and community media</li>
        <li>Maintain website, account, server, and community security</li>
        <li>Understand website and service usage</li>
        <li>Improve SRA events, systems, tools, content, and community experiences</li>
        <li>Maintain administrative, financial, moderation, and competition records</li>
        <li>Comply with applicable legal obligations</li>
        <li>Establish, exercise, or defend legal rights</li>
        <li>Support other legitimate purposes consistent with the context in which information was provided</li>
      </ul>
      <p className={BODY_TEXT}>
        We may also use information for another purpose disclosed at the time it is collected or with
        your consent where required.
      </p>

      {/* ── Legal Bases for Processing ─────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Legal Bases for Processing</h2>
      <p className={BODY_TEXT}>
        Where applicable law requires a legal basis for processing personal information, SRA may rely
        on:
      </p>
      <ul className={LIST}>
        <li>Your consent</li>
        <li>Actions taken at your request</li>
        <li>Performance of an agreement or provision of a requested service</li>
        <li>SRA&rsquo;s legitimate interests in operating and protecting the community</li>
        <li>Competition administration and enforcement of league rules</li>
        <li>Compliance with legal obligations</li>
        <li>The establishment, exercise, or defense of legal claims</li>
        <li>Another lawful basis available under applicable law</li>
      </ul>
      <p className={BODY_TEXT}>
        The applicable legal basis may depend on the information involved and the context in which it
        is collected.
      </p>

      {/* ── Cookies and Similar Technologies ───────────────────────────── */}
      <h2 className={SECTION_HEADING}>Cookies and Similar Technologies</h2>
      <p className={BODY_TEXT}>The SRA website may use cookies and similar technologies to support:</p>
      <ul className={LIST}>
        <li>Account authentication</li>
        <li>Website security</li>
        <li>Session management</li>
        <li>Website functionality</li>
        <li>Saved preferences</li>
        <li>Analytics and performance measurement</li>
        <li>Embedded videos, livestreams, or social media features</li>
        <li>Technical troubleshooting and service improvement</li>
      </ul>
      <p className={BODY_TEXT}>
        Some cookies may be placed by third-party services embedded in or connected to the website.
      </p>
      <p className={BODY_TEXT}>
        You may be able to control cookies through your browser settings or through website preference
        tools where available. Disabling certain technologies may prevent portions of the website from
        functioning properly.
      </p>

      {/* ── How We Disclose Information ────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>How We Disclose Information</h2>
      <p className={BODY_TEXT}>
        SRA may disclose information when reasonably necessary to operate the community, administer
        competition, provide requested services, maintain security, or comply with legal obligations.
      </p>
      <p className={BODY_TEXT}>Recipients may include:</p>
      <ul className={LIST}>
        <li>SRA administrators, moderators, stewards, broadcasters, and authorized volunteers</li>
        <li>Website hosting, infrastructure, server hosting, and technology providers</li>
        <li>Authentication and account connection providers</li>
        <li>Racing platforms, game services, and competition management tools</li>
        <li>Discord, Steam, SimGrid, and similar community or competition platforms where used</li>
        <li>Analytics, security, and website performance providers</li>
        <li>Email, messaging, and communication providers</li>
        <li>Livestreaming, video hosting, and social media platforms</li>
        <li>Donation, subscription, payment, and merchandise providers</li>
        <li>Professional advisers such as attorneys, accountants, consultants, and insurers</li>
        <li>Government authorities or other parties when required by law</li>
        <li>
          Parties necessary to protect SRA, its members, its property, or the safety and integrity of
          the community
        </li>
      </ul>
      <p className={BODY_TEXT}>
        Information may also be disclosed in connection with a reorganization, transfer of operations,
        financing, merger, sale of assets, or similar transaction.
      </p>
      <p className={BODY_TEXT}>
        Access to non-public information is intended to be limited to individuals and providers who
        reasonably require it for their responsibilities.
      </p>

      {/* ── Third-Party Platforms and Services ─────────────────────────── */}
      <h2 className={SECTION_HEADING}>Third-Party Platforms and Services</h2>
      <p className={BODY_TEXT}>
        SRA relies on or links to third-party platforms that may include Steam, Discord, SimGrid,
        Patreon, PayPal, Cash App, Venmo, Exclaim, Twitch, YouTube, game publishers, server providers,
        and other community or competition services.
      </p>
      <p className={BODY_TEXT}>
        These services may collect information directly from you or receive information when you
        interact with their features. Their collection and use of information are governed by their
        respective privacy policies, account settings, and terms.
      </p>
      <p className={BODY_TEXT}>
        SRA does not control the independent privacy or security practices of third-party platforms. We
        encourage members to review the policies and account permissions of each service they use.
      </p>
      <p className={BODY_TEXT}>
        Disconnecting an account from SRA does not necessarily delete information previously collected
        by that third-party platform.
      </p>

      {/* ── Third-Party Links ───────────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Third-Party Links</h2>
      <p className={BODY_TEXT}>
        The SRA website, Discord server, and other community channels may contain links to websites,
        tools, resources, stores, or services operated by third parties.
      </p>
      <p className={BODY_TEXT}>
        SRA does not control the privacy, security, availability, accuracy, or content of independently
        operated third-party services. This Privacy Policy does not apply to information collected
        directly by those parties.
      </p>

      {/* ── Sale, Sharing, and Targeted Advertising ────────────────────── */}
      <h2 className={SECTION_HEADING}>Sale, Sharing, and Targeted Advertising</h2>
      <p className={BODY_TEXT}>SRA does not sell or rent personal information in exchange for monetary payment.</p>
      <p className={BODY_TEXT}>
        Depending on the technologies used on the website and the definitions established under
        applicable privacy laws, certain disclosures to analytics, embedded content, or service
        providers may be considered a &ldquo;sale,&rdquo; &ldquo;sharing,&rdquo; or use for targeted
        advertising.
      </p>
      <p className={BODY_TEXT}>
        Where applicable law provides a right to opt out of such activities, SRA will provide or honor
        an applicable opt-out method as required.
      </p>

      {/* ── Data Retention ──────────────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Data Retention</h2>
      <p className={BODY_TEXT}>
        SRA retains personal information for as long as reasonably necessary for the purposes described
        in this Privacy Policy.
      </p>
      <p className={BODY_TEXT}>Retention periods may depend on:</p>
      <ul className={LIST}>
        <li>The nature of the information</li>
        <li>The purpose for which it was collected</li>
        <li>Whether an account or community relationship remains active</li>
        <li>Competition integrity and historical recordkeeping</li>
        <li>Moderation, stewarding, and disciplinary requirements</li>
        <li>Security and fraud prevention needs</li>
        <li>Financial, legal, or administrative obligations</li>
        <li>Dispute resolution and enforcement of league rules</li>
      </ul>
      <p className={BODY_TEXT}>
        Race results, standings, ratings, records, broadcasts, penalties, and other competition history
        may be retained indefinitely as part of the historical record of SRA.
      </p>
      <p className={BODY_TEXT}>
        When information is no longer reasonably required, SRA may delete, anonymize, aggregate,
        archive, or otherwise dispose of it in accordance with applicable requirements and reasonable
        community practices.
      </p>

      {/* ── Data Security ───────────────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Data Security</h2>
      <p className={BODY_TEXT}>
        SRA uses reasonable administrative, technical, and organizational safeguards designed to protect
        personal information against unauthorized access, loss, misuse, alteration, or disclosure.
      </p>
      <p className={BODY_TEXT}>
        However, no website, server, electronic transmission, account system, or storage service can be
        guaranteed to be completely secure. SRA cannot guarantee the absolute security of information
        transmitted or stored electronically.
      </p>
      <p className={BODY_TEXT}>
        Members are responsible for protecting their devices, passwords, platform accounts,
        authentication credentials, and personal information.
      </p>
      <p className={BODY_TEXT}>
        You should contact SRA promptly if you believe your SRA profile or a connected account has been
        accessed or used without authorization.
      </p>

      {/* ── Your Choices and Privacy Rights ────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Your Choices and Privacy Rights</h2>
      <p className={BODY_TEXT}>
        Depending on your location and applicable law, you may have the right to request:
      </p>
      <ul className={LIST}>
        <li>Access to certain personal information</li>
        <li>Correction of inaccurate information</li>
        <li>Deletion of certain information</li>
        <li>A copy of certain information in a portable format</li>
        <li>Information about how personal information is used or disclosed</li>
        <li>Withdrawal of consent where processing is based on consent</li>
        <li>Restriction of certain processing</li>
        <li>Opt-out of certain sales, sharing, or targeted advertising activities</li>
        <li>Appeal of certain decisions concerning a privacy request</li>
      </ul>
      <p className={BODY_TEXT}>You may also be able to:</p>
      <ul className={LIST}>
        <li>Update certain profile information through your SRA account</li>
        <li>Disconnect a Steam, Discord, or other supported account</li>
        <li>Adjust privacy settings directly through third-party platforms</li>
        <li>Leave the SRA Discord community</li>
        <li>Unsubscribe from promotional emails using the link provided in the message</li>
        <li>Request closure or deletion of an SRA profile</li>
      </ul>
      <p className={BODY_TEXT}>
        Closing an account or leaving the community may not remove public competition results,
        historical records, livestreams, published media, moderation records, or information that SRA
        is permitted or required to retain.
      </p>
      <p className={BODY_TEXT}>
        SRA may take reasonable steps to verify your identity and authority before processing a request.
        Certain requests may be limited or denied where permitted by law, including when retention is
        necessary for competition integrity, security, legal compliance, recordkeeping, or the rights of
        others.
      </p>
      <p className={BODY_TEXT}>
        Nothing in this Privacy Policy is intended to provide rights beyond those required by applicable
        law.
      </p>

      {/* ── Children's Privacy ──────────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Children&rsquo;s Privacy</h2>
      <p className={BODY_TEXT}>
        SRA services are intended for individuals who meet the minimum age requirements of the
        platforms used to access the community. SRA&rsquo;s website and services are not directed to
        children under the age of 13.
      </p>
      <p className={BODY_TEXT}>
        SRA does not knowingly collect personal information from a child under 13. A person under the
        age of majority in their location should participate only with the permission and appropriate
        supervision of a parent or legal guardian.
      </p>
      <p className={BODY_TEXT}>
        If SRA becomes aware that personal information has been collected from a child under 13 without
        appropriate authorization, we will take reasonable steps to review and, where appropriate,
        delete the information.
      </p>
      <p className={BODY_TEXT}>
        A parent or legal guardian who believes a child has provided personal information to SRA may
        contact us using the information below.
      </p>

      {/* ── International Visitors ─────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>International Visitors</h2>
      <p className={BODY_TEXT}>SRA is operated from the United States.</p>
      <p className={BODY_TEXT}>
        If you access SRA services from outside the United States, information may be transferred to,
        processed, or stored in the United States or in other jurisdictions where SRA or its service
        providers operate.
      </p>
      <p className={BODY_TEXT}>
        Privacy and data protection laws in those jurisdictions may differ from the laws in your
        location. Where required by applicable law, appropriate measures will be used in connection
        with international transfers of personal information.
      </p>

      {/* ── Changes to This Privacy Policy ─────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Changes to This Privacy Policy</h2>
      <p className={BODY_TEXT}>
        SRA may update this Privacy Policy to reflect changes in our website, supported racing
        platforms, community services, technology, data practices, service providers, or applicable
        requirements.
      </p>
      <p className={BODY_TEXT}>
        When changes are made, the revised policy will be posted on this page with an updated
        &ldquo;Last Updated&rdquo; date.
      </p>
      <p className={BODY_TEXT}>
        We encourage members and website visitors to review this Privacy Policy periodically.
      </p>

      {/* ── Contact Information ────────────────────────────────────────── */}
      <h2 className={SECTION_HEADING}>Contact Information</h2>
      <p className={BODY_TEXT}>If you have any questions, concerns or policy requests, create an admin ticket in the Sim Racing Alliance Discord server.</p>
    </section>
  );
}
