// A @cardog-icons manufacturer icon, served as a static file from
// public/car-logos/ (generated by scripts/build-car-logos.ts).
//
// Use this, never @cardog-icons/react's <Icon>: that inlines 1–75 KB of SVG
// path data per render (a standings table drew one per row — ~1 MB per view),
// and importing it from a client component ships the whole 4.5 MB package to
// the browser, since <Icon name=…> resolves at runtime and can't be
// tree-shaken. An <img> costs a few bytes and the browser caches the file.
//
// The icons use hard-coded fills (no currentColor), so nothing is lost by
// rendering them through <img>. No hooks, so it renders from server and
// client components alike.
export function CarIcon({ name, size, alt = '' }: { name: string; size: number; alt?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- static SVG, nothing for the optimizer to do
    <img
      src={`/car-logos/${name}.svg`}
      alt={alt}
      width={size}
      height={size}
      decoding="async"
      className="shrink-0"
    />
  );
}
