export type LeaderboardEntry = { rank: number; name: string; value: string };
export type LeaderboardCategory = {
  key: string;
  label: string;
  valueLabel: string;
  entries: LeaderboardEntry[];
};

export const LEADERBOARDS: LeaderboardCategory[] = [
  {
    key: 'all-time-laps',
    label: 'All-Time Laps',
    valueLabel: 'Laps',
    entries: [
      { rank: 1, name: 'Fire Queso', value: '44,494' },
      { rank: 2, name: 'Joel Moffatt', value: '41,348' },
      { rank: 3, name: 'Dan Cran', value: '37,349' },
      { rank: 4, name: 'Guy Manperson', value: '34,707' },
      { rank: 5, name: 'Jeremy Yaron', value: '33,474' },
      { rank: 6, name: 'Kelvin Lau', value: '31,636' },
      { rank: 7, name: 'Pat Cockcroft', value: '28,794' },
      { rank: 8, name: 'Selena Boonstra', value: '28,585' },
      { rank: 9, name: 'Darren Robichaud', value: '27,369' },
      { rank: 10, name: 'Timothy Flammger', value: '27,305' },
      { rank: 11, name: 'Bryan Anderson', value: '24,885' },
      { rank: 12, name: 'Gomer Wilson', value: '24,492' },
      { rank: 13, name: 'Thomas Olhausen', value: '24,141' },
      { rank: 14, name: 'Al Lotufo', value: '23,783' },
      { rank: 15, name: 'Travis Robinson', value: '23,483' },
      { rank: 16, name: 'Curtis Lee', value: '23,470' },
      { rank: 17, name: 'Panzo Rigatoni', value: '22,880' },
      { rank: 18, name: 'Ramon Lorenzo', value: '22,823' },
      { rank: 19, name: 'Danny Durrance', value: '21,956' },
      { rank: 20, name: 'Mr Sir', value: '21,304' },
      { rank: 21, name: 'Jason Yaron', value: '21,274' },
      { rank: 22, name: 'Richie Wood', value: '20,865' },
      { rank: 23, name: 'Jason Allen', value: '20,119' },
      { rank: 24, name: 'Phillipe Enis Müller', value: '19,746' },
      { rank: 25, name: 'Eric Boardman', value: '19,435' },
      { rank: 26, name: 'Wilder Vargas', value: '18,942' },
      { rank: 27, name: 'Jeff Spangler', value: '18,700' },
      { rank: 28, name: 'Jon Crown', value: '18,564' },
      { rank: 29, name: 'Travis Nordstrom', value: '18,488' },
      { rank: 30, name: 'Eric Marecki', value: '18,428' },
      { rank: 31, name: 'Arct', value: '18,402' },
      { rank: 32, name: 'Raf CAB', value: '18,211' },
      { rank: 33, name: 'Anton Rushevich', value: '17,846' },
      { rank: 34, name: 'Sean Curcio', value: '17,833' },
      { rank: 35, name: 'Ryan Yee™', value: '17,564' },
      { rank: 36, name: 'Michael Jeffries', value: '17,466' },
      { rank: 37, name: 'Josh Damiani', value: '17,264' },
      { rank: 38, name: 'Jeremy Mercer', value: '17,133' },
      { rank: 39, name: 'Dominic Duran', value: '16,874' },
      { rank: 40, name: 'Matthew Schwartz', value: '16,288' },
      { rank: 41, name: 'Pauleh Hartman', value: '16,239' },
      { rank: 42, name: 'Douglas Mitchell', value: '15,910' },
      { rank: 43, name: 'Matt Anastasi', value: '15,671' },
      { rank: 44, name: 'Ethan Marvin', value: '15,592' },
      { rank: 45, name: 'Stephen Pellerin', value: '15,589' },
      { rank: 46, name: 'Jon Archie', value: '15,486' },
      { rank: 47, name: 'Bailey Kish', value: '15,427' },
      { rank: 48, name: 'Jacob Palmieri', value: '15,338' },
      { rank: 49, name: 'Collin Dunham', value: '15,020' },
      { rank: 50, name: 'Ivan McCroat', value: '14,974' },
    ],
  },
  {
    key: 'wins',
    label: 'Wins',
    valueLabel: 'Wins',
    entries: [
      { rank: 1, name: 'Michael Moening', value: '23' },
      { rank: 2, name: 'Anton Rushevich', value: '15' },
      { rank: 3, name: 'Matt Leeman', value: '14' },
      { rank: 4, name: 'Ryan Yee™', value: '14' },
      { rank: 5, name: 'Jeremy Yaron', value: '10' },
      { rank: 6, name: 'Jeremy Mercer', value: '9' },
      { rank: 7, name: 'Travis Nordstrom', value: '8' },
      { rank: 8, name: 'Big Daddy', value: '7' },
      { rank: 9, name: 'Aaron Anderson', value: '7' },
      { rank: 10, name: 'Thomas Olhausen', value: '7' },
      { rank: 11, name: 'Andrew Rados', value: '7' },
      { rank: 12, name: 'Amos Movo', value: '7' },
      { rank: 13, name: 'Diego Paul Fimbres Casas', value: '6' },
      { rank: 14, name: 'Evan Kim', value: '6' },
      { rank: 15, name: 'Mr Sir', value: '6' },
      { rank: 16, name: 'Kelvin Lau', value: '6' },
      { rank: 17, name: 'Jeff Spangler', value: '6' },
      { rank: 18, name: 'Matt Anderson', value: '6' },
      { rank: 19, name: 'Thiago Dinarte', value: '6' },
      { rank: 20, name: 'Mason Moffett', value: '6' },
      { rank: 21, name: 'Douglas Mitchell', value: '5' },
      { rank: 22, name: 'Josh Damiani', value: '5' },
      { rank: 23, name: 'Ren Aoki', value: '5' },
      { rank: 24, name: 'Roger Rodriguez', value: '5' },
      { rank: 25, name: 'DJ Watts', value: '5' },
      { rank: 26, name: 'Nick Wagner', value: '5' },
      { rank: 27, name: 'Caleb Craig', value: '5' },
      { rank: 28, name: 'Landon Drebes', value: '5' },
      { rank: 29, name: 'Chilsy', value: '5' },
      { rank: 30, name: 'Zack Dupuis', value: '5' },
      { rank: 31, name: 'Renato Dornelles', value: '5' },
      { rank: 32, name: 'Michael McWeezerson', value: '5' },
      { rank: 33, name: 'Brooker Quigg', value: '4' },
      { rank: 34, name: 'Eric Boardman', value: '4' },
      { rank: 35, name: 'Austin Sawyer', value: '4' },
      { rank: 36, name: 'Konor Fewkes', value: '4' },
      { rank: 37, name: 'Kevin Kovach', value: '4' },
      { rank: 38, name: 'Daniel Gutierrez', value: '4' },
      { rank: 39, name: 'Pat Cockcroft', value: '4' },
      { rank: 40, name: 'Ian Kreigar', value: '4' },
      { rank: 41, name: 'Vincent Nicolet', value: '4' },
      { rank: 42, name: 'Christian Lorenzo', value: '4' },
      { rank: 43, name: 'Justin MacKechnie', value: '4' },
      { rank: 44, name: 'Ein Byron', value: '4' },
      { rank: 45, name: 'Roy Keay', value: '4' },
      { rank: 46, name: 'Mike Geno', value: '4' },
      { rank: 47, name: 'Dawson Tremelling', value: '4' },
      { rank: 48, name: 'Mark DC', value: '4' },
      { rank: 49, name: 'Kevin Johnston', value: '4' },
      { rank: 50, name: 'Matt Kirkland', value: '4' },
    ],
  },
  {
    key: 'podiums',
    label: 'Podiums',
    valueLabel: 'Podiums',
    entries: [
      { rank: 1, name: 'Michael Moening', value: '39' },
      { rank: 2, name: 'Jeremy Mercer', value: '34' },
      { rank: 3, name: 'Travis Nordstrom', value: '26' },
      { rank: 4, name: 'Jeff Spangler', value: '25' },
      { rank: 5, name: 'Anton Rushevich', value: '25' },
      { rank: 6, name: 'Matt Leeman', value: '23' },
      { rank: 7, name: 'Mr Sir', value: '22' },
      { rank: 8, name: 'Ryan Yee™', value: '21' },
      { rank: 9, name: 'Jeremy Yaron', value: '19' },
      { rank: 10, name: 'Andrew Rados', value: '19' },
      { rank: 11, name: 'Ren Aoki', value: '16' },
      { rank: 12, name: 'Thomas Olhausen', value: '16' },
      { rank: 13, name: 'Michael McWeezerson', value: '16' },
      { rank: 14, name: 'Justin MacKechnie', value: '15' },
      { rank: 15, name: 'Big Daddy', value: '15' },
      { rank: 16, name: 'Thiago Dinarte', value: '15' },
      { rank: 17, name: 'Diego Paul Fimbres Casas', value: '14' },
      { rank: 18, name: 'Selena Boonstra', value: '14' },
      { rank: 19, name: 'Shaun Daniels', value: '13' },
      { rank: 20, name: 'Douglas Mitchell', value: '12' },
      { rank: 21, name: 'Michael Jeffries', value: '12' },
      { rank: 22, name: 'Bryan Anderson', value: '12' },
      { rank: 23, name: 'Cory Cercone', value: '12' },
      { rank: 24, name: 'Jarrod Seccombe', value: '12' },
      { rank: 25, name: 'Renato Dornelles', value: '12' },
      { rank: 26, name: 'Amos Movo', value: '12' },
      { rank: 27, name: 'Kelvin Lau', value: '11' },
      { rank: 28, name: 'Jon Archie', value: '11' },
      { rank: 29, name: 'Aaron Anderson', value: '11' },
      { rank: 30, name: 'Ed Kerstetter', value: '11' },
      { rank: 31, name: 'Mason Moffett', value: '11' },
      { rank: 32, name: 'Josh Damiani', value: '10' },
      { rank: 33, name: 'Konor Fewkes', value: '10' },
      { rank: 34, name: 'Jess Osborn', value: '10' },
      { rank: 35, name: 'David Funk', value: '10' },
      { rank: 36, name: 'Stephen Sarver', value: '10' },
      { rank: 37, name: 'DJ Watts', value: '10' },
      { rank: 38, name: 'Nick Wagner', value: '10' },
      { rank: 39, name: 'Matt Anastasi', value: '10' },
      { rank: 40, name: 'Landon Drebes', value: '10' },
      { rank: 41, name: 'Gordon Beverly III', value: '10' },
      { rank: 42, name: 'Quinton Schattner', value: '10' },
      { rank: 43, name: 'Rob Warren', value: '10' },
      { rank: 44, name: 'Kyle Barbour', value: '10' },
      { rank: 45, name: 'Dominic Duran', value: '9' },
      { rank: 46, name: 'Evan Kim', value: '9' },
      { rank: 47, name: 'Kevin Kovach', value: '9' },
      { rank: 48, name: 'Victor Diaz', value: '9' },
      { rank: 49, name: 'Roger Rodriguez', value: '9' },
      { rank: 50, name: 'Nate Specht', value: '9' },
    ],
  },
  {
    key: 'top-10s',
    label: 'Top 10s',
    valueLabel: 'Top 10s',
    entries: [
      { rank: 1, name: 'Jeremy Mercer', value: '88' },
      { rank: 2, name: 'Mr Sir', value: '68' },
      { rank: 3, name: 'Michael Moening', value: '61' },
      { rank: 4, name: 'Travis Nordstrom', value: '55' },
      { rank: 5, name: 'Jeff Spangler', value: '54' },
      { rank: 6, name: 'Stephen Sarver', value: '53' },
      { rank: 7, name: 'Josh Damiani', value: '52' },
      { rank: 8, name: 'Conor Farrell', value: '49' },
      { rank: 9, name: 'Douglas Mitchell', value: '48' },
      { rank: 10, name: 'Selena Boonstra', value: '47' },
      { rank: 11, name: 'Bryan Anderson', value: '44' },
      { rank: 12, name: 'Dan Cran', value: '44' },
      { rank: 13, name: 'Kelvin Lau', value: '43' },
      { rank: 14, name: 'Justin MacKechnie', value: '42' },
      { rank: 15, name: "Peter O'Brien", value: '42' },
      { rank: 16, name: 'Anton Rushevich', value: '42' },
      { rank: 17, name: 'Jon Archie', value: '41' },
      { rank: 18, name: 'Andrew Rados', value: '40' },
      { rank: 19, name: 'Pat Cockcroft', value: '39' },
      { rank: 20, name: 'Alan Leung', value: '39' },
      { rank: 21, name: 'Matt Leeman', value: '38' },
      { rank: 22, name: 'Ren Aoki', value: '38' },
      { rank: 23, name: 'DJ Watts', value: '37' },
      { rank: 24, name: 'Ein Byron', value: '37' },
      { rank: 25, name: 'Gomer Wilson', value: '37' },
      { rank: 26, name: 'Phillipe Enis Müller', value: '37' },
      { rank: 27, name: 'Dyck Zipperburn Jr.', value: '37' },
      { rank: 28, name: 'Jess Osborn', value: '35' },
      { rank: 29, name: 'Panzo Rigatoni', value: '35' },
      { rank: 30, name: 'Jeremy Yaron', value: '35' },
      { rank: 31, name: 'Mike Geno', value: '35' },
      { rank: 32, name: 'Thomas Olhausen', value: '35' },
      { rank: 33, name: 'Diego Paul Fimbres Casas', value: '34' },
      { rank: 34, name: 'Matt Anastasi', value: '33' },
      { rank: 35, name: 'Jason Allen', value: '32' },
      { rank: 36, name: 'Shaun Daniels', value: '32' },
      { rank: 37, name: 'Niko Suave', value: '32' },
      { rank: 38, name: 'Mark DC', value: '32' },
      { rank: 39, name: 'Curtis Lee', value: '31' },
      { rank: 40, name: 'Colin Shea', value: '30' },
      { rank: 41, name: 'Guy Manperson', value: '30' },
      { rank: 42, name: 'Koa Dromo', value: '29' },
      { rank: 43, name: 'Thiago Dinarte', value: '29' },
      { rank: 44, name: 'Nate Specht', value: '28' },
      { rank: 45, name: 'Big Daddy', value: '28' },
      { rank: 46, name: 'Chris Sweeney', value: '28' },
      { rank: 47, name: 'Omar Escorcia', value: '28' },
      { rank: 48, name: 'Brooker Quigg', value: '27' },
      { rank: 49, name: 'Eric Boardman', value: '27' },
      { rank: 50, name: 'Travis Robinson', value: '27' },
    ],
  },
  {
    key: 'poles',
    label: 'Pole Positions',
    valueLabel: 'Poles',
    entries: [
      { rank: 1, name: 'Michael Moening', value: '19' },
      { rank: 2, name: 'Anton Rushevich', value: '14' },
      { rank: 3, name: 'Matt Leeman', value: '13' },
      { rank: 4, name: 'Ryan Yee™', value: '10' },
      { rank: 5, name: 'Amos Movo', value: '9' },
      { rank: 6, name: 'Jeff Spangler', value: '8' },
      { rank: 7, name: 'Jeremy Yaron', value: '8' },
      { rank: 8, name: 'Big Daddy', value: '8' },
      { rank: 9, name: 'Ian Kreigar', value: '7' },
      { rank: 10, name: 'Aaron Anderson', value: '7' },
      { rank: 11, name: 'Andrew Rados', value: '7' },
      { rank: 12, name: 'Mason Moffett', value: '7' },
      { rank: 13, name: 'Travis Nordstrom', value: '6' },
      { rank: 14, name: 'Diego Paul Fimbres Casas', value: '6' },
      { rank: 15, name: 'Josh Damiani', value: '6' },
      { rank: 16, name: 'Loukas Klentzeris', value: '6' },
      { rank: 17, name: 'Jeremy Mercer', value: '6' },
      { rank: 18, name: 'Alex Krochik', value: '6' },
      { rank: 19, name: 'Roy Keay', value: '6' },
      { rank: 20, name: 'Zack Dupuis', value: '6' },
      { rank: 21, name: 'Dieveem Galindo', value: '6' },
      { rank: 22, name: 'Renato Dornelles', value: '6' },
      { rank: 23, name: 'Simon Goriel', value: '6' },
      { rank: 24, name: 'Kevin Kovach', value: '5' },
      { rank: 25, name: 'David Funk', value: '5' },
      { rank: 26, name: 'Jacob Rutkoske', value: '5' },
      { rank: 27, name: 'Gareth Sykes', value: '5' },
      { rank: 28, name: 'Cube Master', value: '5' },
      { rank: 29, name: 'Landon Drebes', value: '5' },
      { rank: 30, name: 'Kelvin Lau', value: '5' },
      { rank: 31, name: 'Ein Byron', value: '5' },
      { rank: 32, name: 'Thomas Olhausen', value: '5' },
      { rank: 33, name: 'Sean Leitch', value: '5' },
      { rank: 34, name: 'Thiago Dinarte', value: '5' },
      { rank: 35, name: 'Dae Hee Yun', value: '4' },
      { rank: 36, name: 'Hesham Rimzk', value: '4' },
      { rank: 37, name: 'OMG ItsPav', value: '4' },
      { rank: 38, name: 'Roger Rodriguez', value: '4' },
      { rank: 39, name: 'Loïc Normandeau', value: '4' },
      { rank: 40, name: 'Christian Lorenzo', value: '4' },
      { rank: 41, name: 'Nate Bright', value: '4' },
      { rank: 42, name: 'Cory Cercone', value: '4' },
      { rank: 43, name: 'Caleb Craig', value: '4' },
      { rank: 44, name: 'Scott Smith', value: '4' },
      { rank: 45, name: 'Mr Sir', value: '4' },
      { rank: 46, name: 'CJ Meeks', value: '4' },
      { rank: 47, name: 'Sean Williams', value: '4' },
      { rank: 48, name: 'Dawson Tremelling', value: '4' },
      { rank: 49, name: 'Phillipe Enis Müller', value: '4' },
      { rank: 50, name: 'Matt Kirkland', value: '4' },
    ],
  },
  {
    key: 'tracks',
    label: 'Tracks',
    valueLabel: 'Laps',
    entries: [
      { rank: 1, name: 'Kyalami', value: '253,649' },
      { rank: 2, name: 'Spa Francorchamps', value: '248,965' },
      { rank: 3, name: 'Suzuka', value: '248,309' },
      { rank: 4, name: 'Barcelona', value: '243,137' },
      { rank: 5, name: 'Indianapolis', value: '225,631' },
      { rank: 6, name: 'Misano', value: '212,986' },
      { rank: 7, name: 'Imola', value: '207,499' },
      { rank: 8, name: 'Nürburgring', value: '206,955' },
      { rank: 9, name: 'Paul Ricard', value: '206,311' },
      { rank: 10, name: 'Watkins Glen', value: '201,929' },
      { rank: 11, name: 'Laguna Seca', value: '200,599' },
      { rank: 12, name: 'Hungaroring', value: '200,121' },
      { rank: 13, name: 'Brands Hatch', value: '192,532' },
      { rank: 14, name: 'Silverstone', value: '182,672' },
      { rank: 15, name: 'Valencia', value: '178,427' },
      { rank: 16, name: 'Zolder', value: '159,833' },
      { rank: 17, name: 'Mount Panorama', value: '159,623' },
      { rank: 18, name: 'Oulton Park', value: '158,378' },
      { rank: 19, name: 'Circuit of The Americas', value: '153,310' },
      { rank: 20, name: 'Donington Park', value: '151,927' },
      { rank: 21, name: 'Monza', value: '146,082' },
      { rank: 22, name: 'Zandvoort', value: '131,662' },
      { rank: 23, name: 'Red Bull Ring', value: '125,482' },
      { rank: 24, name: 'Snetterton', value: '122,434' },
      { rank: 25, name: 'Nordschleife', value: '22,163' },
    ],
  },
  {
    key: 'cars',
    label: 'Cars',
    valueLabel: 'Laps',
    entries: [
      { rank: 1, name: 'McLaren 720S GT3 Evo (2023)', value: '620,111' },
      { rank: 2, name: 'Ferrari 296 GT3 (2023)', value: '598,986' },
      { rank: 3, name: 'Porsche 992 GT3 R (2023)', value: '498,458' },
      { rank: 4, name: 'BMW M4 GT3 (2022)', value: '407,812' },
      { rank: 5, name: 'AMR V8 Vantage GT3 (2019)', value: '349,132' },
      { rank: 6, name: 'Mercedes-AMG GT3 EVO (2020)', value: '229,679' },
      { rank: 7, name: 'Lamborghini Huracán GT3 EVO2 (2023)', value: '224,875' },
      { rank: 8, name: 'McLaren 720S GT3 (2019)', value: '188,451' },
      { rank: 9, name: 'Ford Mustang GT3 (2024)', value: '186,696' },
      { rank: 10, name: 'Porsche 991 II GT3 R (2019)', value: '178,728' },
      { rank: 11, name: 'Honda NSX GT3 Evo (2019)', value: '177,721' },
      { rank: 12, name: 'Lexus RC F GT3 (2016)', value: '167,776' },
      { rank: 13, name: 'Ferrari 488 GT3 Evo (2020)', value: '164,630' },
      { rank: 14, name: 'Audi R8 LMS GT3 Evo 2 (2022)', value: '158,416' },
      { rank: 15, name: 'Bentley Continental GT3 (2018)', value: '74,910' },
      { rank: 16, name: 'Nissan GT-R Nismo GT3 (2018)', value: '71,524' },
      { rank: 17, name: 'Lamborghini Huracán GT3 EVO (2019)', value: '36,565' },
      { rank: 18, name: 'BMW M2 Club Sport Racing (2020)', value: '26,808' },
      { rank: 19, name: 'Emil Frey Jaguar G3 (2012)', value: '19,763' },
      { rank: 20, name: 'Porsche 992 GT3 Cup (2021)', value: '17,742' },
      { rank: 21, name: 'Porsche 718 Cayman GT4 CS (2019)', value: '13,544' },
      { rank: 22, name: 'Chevrolet Camaro GT4 (2017)', value: '11,722' },
      { rank: 23, name: 'Ferrari 488 GT3 (2018)', value: '9,793' },
      { rank: 24, name: 'Audi R8 LMS Evo (2019)', value: '9,690' },
      { rank: 25, name: 'Mercedes-AMG GT4 (2016)', value: '9,224' },
      { rank: 26, name: 'Aston Martin Vantage GT4 (2018)', value: '7,467' },
      { rank: 27, name: 'Lamborghini Huracán ST EVO2 (2021)', value: '7,442' },
      { rank: 28, name: 'Mercedes-AMG GT3 (2015)', value: '7,229' },
      { rank: 29, name: 'AMR V12 Vantage GT3 (2013)', value: '7,119' },
      { rank: 30, name: 'BMW M6 GT3 (2017)', value: '5,586' },
      { rank: 31, name: 'KTM X-Bow GT4 (2016)', value: '5,166' },
      { rank: 32, name: 'Maserati MC20 GT2 (2024)', value: '4,327' },
      { rank: 33, name: 'Ginetta G55 GT4 (2012)', value: '4,315' },
      { rank: 34, name: 'McLaren 570S GT4 (2016)', value: '4,176' },
      { rank: 35, name: 'Alpine A110 GT4 (2018)', value: '3,976' },
      { rank: 36, name: 'KTM X-Bow GT2 (2024)', value: '3,464' },
      { rank: 37, name: 'Ferrari 488 Challenge Evo (2020)', value: '3,242' },
      { rank: 38, name: 'BMW M4 GT4 (2018)', value: '2,612' },
      { rank: 39, name: 'Reiter Engineering R-EX GT3 (2017)', value: '2,366' },
      { rank: 40, name: 'Maserati MC GT4 (2016)', value: '2,312' },
      { rank: 41, name: 'Audi R8 LMS GT2 (2024)', value: '2,304' },
      { rank: 42, name: 'Porsche 991 GT3 R (2018)', value: '2,163' },
      { rank: 43, name: 'Mercedes-AMG GT2 (2024)', value: '2,102' },
      { rank: 44, name: 'Audi R8 LMS GT4 (2018)', value: '1,868' },
      { rank: 45, name: 'McLaren 650S GT3 (2015)', value: '1,458' },
      { rank: 46, name: 'Porsche 991 II GT3 Cup (2017)', value: '1,308' },
      { rank: 47, name: 'Porsche 911 GT2 RS CS Evo (2024)', value: '1,177' },
      { rank: 48, name: 'Audi R8 LMS (2015)', value: '1,128' },
      { rank: 49, name: 'Nissan GT-R Nismo GT3 (2015)', value: '1,016' },
      { rank: 50, name: 'Lamborghini Huracán GT3 (2015)', value: '725' },
    ],
  },
];
